Components/SongListViewComponent.cs
using RazorPages_AlbumProject.Data;
using Microsoft.AspNetCore.Mvc;

namespace K_popbibliotek.Components
{
    public class SongListViewComponent:ViewComponent
    {
        private readonly ISong iSong;

        public SongListViewComponent(ISong ISong)
        {
            this.iSong = ISong;
        }
        public IViewComponentResult Invoke(int recordId)
        {
            var items = iSong.GetAll().Where(x => x.RecordID == recordId).ToList();
            return View(items);
        }
    }
}

Pages/Albums/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using AlbumLogger.Data;
using RazorPages_AlbumProject.Data;

namespace RazorPages_AlbumProject.Pages.Albums
{
    public class CreateModel : PageModel
    {
        private readonly IAlbum AlbumRep;

        public CreateModel(IAlbum AlbumRep)
        {
            this.AlbumRep = AlbumRep;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Album Album { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync(Album album)
        {
          if (!ModelState.IsValid || AlbumRep == null || Album == null)
            {
                return Page();
            }

            AlbumRep.Add(Album);
            
            AlbumRep.SaveChanges();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Albums/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AlbumLogger.Data;
using RazorPages_AlbumProject.Data;

namespace RazorPages_AlbumProject.Pages.Albums
{
    public class DeleteModel : PageModel
    {
        private readonly IAlbum AlbumRep;

        public DeleteModel(IAlbum AlbumRep)
        {
            this.AlbumRep = AlbumRep;
        }


        [BindProperty]
      public Album Album { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int id)
        {
            if (AlbumRep == null)
            {
                return NotFound();
            }

            var album = AlbumRep.GetById(id);

            if (album == null)
            {
                return NotFound();
            }
            else 
            {
                Album = album;
            }
            return Page();
        }

        public async Task<IActionResult> OnPost(int id)
        {
            if (AlbumRep == null)
            {
                return NotFound();
            }
            var album = AlbumRep.GetById(id);

            if (album != null)
            {
                Album = album;
                AlbumRep.Delete(album);
                AlbumRep.SaveChanges();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Albums/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AlbumLogger.Data;
using RazorPages_AlbumProject.Data;

namespace RazorPages_AlbumProject.Pages.Albums
{
    public class DetailsModel : PageModel
    {
        private readonly IAlbum AlbumRep;

        public DetailsModel(IAlbum AlbumRep)
        {
           this.AlbumRep = AlbumRep;
        }

      public Album Album { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int id)
        {


            if (AlbumRep == null)
            {
                return NotFound();
            }
            
            var album = AlbumRep.GetById(id);
            if (album == null)
            {
                return NotFound();
            }
            else 
            {
                Album = album;
            }
            return Page();
        }
    }
}

Pages/Albums/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlbumLogger.Data;
using RazorPages_AlbumProject.Data;

namespace RazorPages_AlbumProject.Pages.Albums
{
    public class EditModel : PageModel
    {
        private readonly IAlbum AlbumRep;

        public EditModel(IAlbum AlbumRep)
        {
            this.AlbumRep = AlbumRep;
        }

        [BindProperty]
        public Album Album { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int id)
        {
            if (AlbumRep == null)
            {
                return NotFound();
            }

            var album = AlbumRep.GetById(id);
            if (album == null)
            {
                return NotFound();
            }
            Album = album;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }


            try
            {
                AlbumRep.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AlbumExists(Album.AlbumId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AlbumExists(int id)
        {
          return AlbumRep.GetAll().Any(e => e.AlbumId == id);
        }
    }
}

Pages/Albums/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AlbumLogger.Data;
using RazorPages_AlbumProject.Data;

namespace RazorPages_AlbumProject.Pages.Albums
{
    public class IndexModel : PageModel
    {
        private readonly IAlbum AlbumRep;

        public IndexModel(IAlbum AlbumRep)
        {
            this.AlbumRep = AlbumRep;
        }

        public IList<Album> Album { get;set; } = default!;

        public async Task OnGetAsync()
        {
            if (AlbumRep != null)
            {
                Album = AlbumRep.GetAll().ToList();
            }
        }
    }
}

Pages/Songs/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using AlbumLogger.Data;
using RazorPages_AlbumProject.Data;

namespace RazorPages_AlbumProject.Pages.Songs
{
    public class CreateModel : PageModel
    {
        private readonly ISong songRep;

        public CreateModel(ISong SongRep)
        {
            songRep = SongRep;
        }


        public IActionResult OnGet(int id)
        {
            Song = new Song();
            Song.RecordID = id;
            return Page();
        }

        [BindProperty]
        public Song Song { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync(Song song)
        {
            if (!ModelState.IsValid || songRep == null || Song == null)
            {
                return Page();
            }

            songRep.Add(song);
            songRep.SaveChanges();

            return RedirectToPage("/Albums/Details", new { id = Song.RecordID });
        }
    }
}

Pages/Songs/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AlbumLogger.Data;
using RazorPages_AlbumProject.Data;

namespace RazorPages_AlbumProject.Pages.Songs
{
    public class DeleteModel : PageModel
    {
        private readonly RazorPages_AlbumProject.Data.RazorPages_AlbumProjectContext _context;

        public DeleteModel(RazorPages_AlbumProject.Data.RazorPages_AlbumProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Song Song { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Song == null)
            {
                return NotFound();
            }

            var song = await _context.Song.FirstOrDefaultAsync(m => m.SongId == id);

            if (song == null)
            {
                return NotFound();
            }
            else 
            {
                Song = song;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Song == null)
            {
                return NotFound();
            }
            var song = await _context.Song.FindAsync(id);

            if (song != null)
            {
                Song = song;
                _context.Song.Remove(Song);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Songs/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AlbumLogger.Data;
using RazorPages_AlbumProject.Data;

namespace RazorPages_AlbumProject.Pages.Songs
{
    public class DetailsModel : PageModel
    {
        private readonly RazorPages_AlbumProject.Data.RazorPages_AlbumProjectContext _context;

        public DetailsModel(RazorPages_AlbumProject.Data.RazorPages_AlbumProjectContext context)
        {
            _context = context;
        }

      public Song Song { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Song == null)
            {
                return NotFound();
            }

            var song = await _context.Song.FirstOrDefaultAsync(m => m.SongId == id);
            if (song == null)
            {
                return NotFound();
            }
            else 
            {
                Song = song;
            }
            return Page();
        }
    }
}

Pages/Songs/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlbumLogger.Data;
using RazorPages_AlbumProject.Data;

namespace RazorPages_AlbumProject.Pages.Songs
{
    public class EditModel : PageModel
    {
        private readonly RazorPages_AlbumProject.Data.RazorPages_AlbumProjectContext _context;

        public EditModel(RazorPages_AlbumProject.Data.RazorPages_AlbumProjectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Song Song { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Song == null)
            {
                return NotFound();
            }

            var song =  await _context.Song.FirstOrDefaultAsync(m => m.SongId == id);
            if (song == null)
            {
                return NotFound();
            }
            Song = song;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Song).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SongExists(Song.SongId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool SongExists(int id)
        {
          return (_context.Song?.Any(e => e.SongId == id)).GetValueOrDefault();
        }
    }
}

Pages/Albums/Create.cshtml
@page
@model RazorPages_AlbumProject.Pages.Albums.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Album</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Album.ArtistName" class="control-label"></label>
                <input asp-for="Album.ArtistName" class="form-control" />
                <span asp-validation-for="Album.ArtistName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Album.AlbumName" class="control-label"></label>
                <input asp-for="Album.AlbumName" class="form-control" />
                <span asp-validation-for="Album.AlbumName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Album.ReleaseDate" class="control-label"></label>
                <input asp-for="Album.ReleaseDate" class="form-control" />
                <span asp-validation-for="Album.ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Album.RecordCompany" class="control-label"></label>
                <input asp-for="Album.RecordCompany" class="form-control" />
                <span asp-validation-for="Album.RecordCompany" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Albums/Delete.cshtml
@page
@model RazorPages_AlbumProject.Pages.Albums.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Album.ArtistName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Album.ArtistName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Album.AlbumName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Album.AlbumName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Album.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Album.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Album.RecordCompany)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Album.RecordCompany)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Album.AlbumId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Albums/Details.cshtml
@page
@model RazorPages_AlbumProject.Pages.Albums.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="row">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Album.ArtistName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Album.ArtistName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Album.AlbumName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Album.AlbumName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Album.ReleaseDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Album.ReleaseDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Album.RecordCompany)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Album.RecordCompany)
            </dd>
            <dd class="col-sm-10">
                @await Component.InvokeAsync("SongList",new {recordId=Model.Album.AlbumId})
            </dd>
        </dl>

    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Album?.AlbumId">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Albums/Edit.cshtml
@page
@model RazorPages_AlbumProject.Pages.Albums.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Album</h4>

<hr />
<p><a asp-page="/Songs/Create" asp-route-id="@Model.Album?.AlbumId">Create Song</a></p>

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Album.AlbumId" />
            <div class="form-group">
                <label asp-for="Album.ArtistName" class="control-label"></label>
                <input asp-for="Album.ArtistName" class="form-control" />
                <span asp-validation-for="Album.ArtistName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Album.AlbumName" class="control-label"></label>
                <input asp-for="Album.AlbumName" class="form-control" />
                <span asp-validation-for="Album.AlbumName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Album.ReleaseDate" class="control-label"></label>
                <input asp-for="Album.ReleaseDate" class="form-control" />
                <span asp-validation-for="Album.ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Album.RecordCompany" class="control-label"></label>
                <input asp-for="Album.RecordCompany" class="form-control" />
                <span asp-validation-for="Album.RecordCompany" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Albums/Index.cshtml
@page
@model RazorPages_AlbumProject.Pages.Albums.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Album[0].ArtistName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Album[0].AlbumName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Album[0].ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Album[0].RecordCompany)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Album) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ArtistName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AlbumName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecordCompany)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.AlbumId">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.AlbumId">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.AlbumId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>